export const SAVE_LIST = 'SAVE_LIST'
export const SAVE_LIST_START = 'SAVE_LIST_START'
export const SAVE_LIST_ERROR = 'SAVE_LIST_ERROR'
export const START_LOGIN = 'START_LOGIN'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT = 'LOGOUT'